// Generated by scripts/generate-scripture.mjs from the vetted eBible-derived
// WEB and KJV resources bundled with BibleReader. Do not edit by hand.
import type { Verse } from "./types";

export const scripture: Record<string, Verse> = {
  "gen-2-22": {
    "id": "gen-2-22",
    "reference": "Genesis 2:22",
    "web": "The LORD God made a woman from the rib which he had taken from the man, and brought her to the man.",
    "kjv": "And the rib, which the LORD God had taken from man, made he a woman, and brought her unto the man."
  },
  "gen-2-23": {
    "id": "gen-2-23",
    "reference": "Genesis 2:23",
    "web": "The man said, “This is now bone of my bones, and flesh of my flesh. She will be called ‘woman,’ because she was taken out of Man.”",
    "kjv": "And Adam said, This is now bone of my bones, and flesh of my flesh: she shall be called Woman, because she was taken out of Man."
  },
  "gen-2-24": {
    "id": "gen-2-24",
    "reference": "Genesis 2:24",
    "web": "Therefore a man will leave his father and his mother, and will join with his wife, and they will be one flesh.",
    "kjv": "Therefore shall a man leave his father and his mother, and shall cleave unto his wife: and they shall be one flesh."
  },
  "gen-4-1": {
    "id": "gen-4-1",
    "reference": "Genesis 4:1",
    "web": "The man knew Eve his wife. She conceived, and gave birth to Cain, and said, “I have gotten a man with the LORD’s help.”",
    "kjv": "And Adam knew Eve his wife; and she conceived, and bare Cain, and said, I have gotten a man from the LORD."
  },
  "gen-4-2": {
    "id": "gen-4-2",
    "reference": "Genesis 4:2",
    "web": "Again she gave birth, to Cain’s brother Abel. Abel was a keeper of sheep, but Cain was a tiller of the ground.",
    "kjv": "And she again bare his brother Abel. And Abel was a keeper of sheep, but Cain was a tiller of the ground."
  },
  "gen-4-25": {
    "id": "gen-4-25",
    "reference": "Genesis 4:25",
    "web": "Adam knew his wife again. She gave birth to a son, and named him Seth, saying, “for God has given me another child instead of Abel, for Cain killed him.”",
    "kjv": "And Adam knew his wife again; and she bare a son, and called his name Seth: For God, said she, hath appointed me another seed instead of Abel, whom Cain slew."
  },
  "gen-4-26": {
    "id": "gen-4-26",
    "reference": "Genesis 4:26",
    "web": "A son was also born to Seth, and he named him Enosh. At that time men began to call on the LORD’s name.",
    "kjv": "And to Seth, to him also there was born a son; and he called his name Enos: then began men to call upon the name of the LORD."
  },
  "gen-5-1": {
    "id": "gen-5-1",
    "reference": "Genesis 5:1",
    "web": "This is the book of the generations of Adam. In the day that God created man, he made him in God’s likeness.",
    "kjv": "This is the book of the generations of Adam. In the day that God created man, in the likeness of God made he him;"
  },
  "gen-5-2": {
    "id": "gen-5-2",
    "reference": "Genesis 5:2",
    "web": "He created them male and female, and blessed them. On the day they were created, he named them Adam.",
    "kjv": "Male and female created he them; and blessed them, and called their name Adam, in the day when they were created."
  },
  "gen-5-3": {
    "id": "gen-5-3",
    "reference": "Genesis 5:3",
    "web": "Adam lived one hundred thirty years, and became the father of a son in his own likeness, after his image, and named him Seth.",
    "kjv": "And Adam lived an hundred and thirty years, and begat a son in his own likeness, after his image; and called his name Seth:"
  },
  "gen-5-4": {
    "id": "gen-5-4",
    "reference": "Genesis 5:4",
    "web": "The days of Adam after he became the father of Seth were eight hundred years, and he became the father of other sons and daughters.",
    "kjv": "And the days of Adam after he had begotten Seth were eight hundred years: and he begat sons and daughters:"
  },
  "gen-5-5": {
    "id": "gen-5-5",
    "reference": "Genesis 5:5",
    "web": "All the days that Adam lived were nine hundred thirty years, then he died.",
    "kjv": "And all the days that Adam lived were nine hundred and thirty years: and he died."
  },
  "gen-5-6": {
    "id": "gen-5-6",
    "reference": "Genesis 5:6",
    "web": "Seth lived one hundred five years, then became the father of Enosh.",
    "kjv": "And Seth lived an hundred and five years, and begat Enos:"
  },
  "gen-5-7": {
    "id": "gen-5-7",
    "reference": "Genesis 5:7",
    "web": "Seth lived after he became the father of Enosh eight hundred seven years, and became the father of other sons and daughters.",
    "kjv": "And Seth lived after he begat Enos eight hundred and seven years, and begat sons and daughters:"
  },
  "gen-5-8": {
    "id": "gen-5-8",
    "reference": "Genesis 5:8",
    "web": "All of the days of Seth were nine hundred twelve years, then he died.",
    "kjv": "And all the days of Seth were nine hundred and twelve years: and he died."
  },
  "gen-5-9": {
    "id": "gen-5-9",
    "reference": "Genesis 5:9",
    "web": "Enosh lived ninety years, and became the father of Kenan.",
    "kjv": "And Enos lived ninety years, and begat Cainan:"
  },
  "gen-5-10": {
    "id": "gen-5-10",
    "reference": "Genesis 5:10",
    "web": "Enosh lived after he became the father of Kenan eight hundred fifteen years, and became the father of other sons and daughters.",
    "kjv": "And Enos lived after he begat Cainan eight hundred and fifteen years, and begat sons and daughters:"
  },
  "gen-5-11": {
    "id": "gen-5-11",
    "reference": "Genesis 5:11",
    "web": "All of the days of Enosh were nine hundred five years, then he died.",
    "kjv": "And all the days of Enos were nine hundred and five years: and he died."
  },
  "gen-5-12": {
    "id": "gen-5-12",
    "reference": "Genesis 5:12",
    "web": "Kenan lived seventy years, then became the father of Mahalalel.",
    "kjv": "And Cainan lived seventy years, and begat Mahalaleel:"
  },
  "gen-5-13": {
    "id": "gen-5-13",
    "reference": "Genesis 5:13",
    "web": "Kenan lived after he became the father of Mahalalel eight hundred forty years, and became the father of other sons and daughters",
    "kjv": "And Cainan lived after he begat Mahalaleel eight hundred and forty years, and begat sons and daughters:"
  },
  "gen-5-14": {
    "id": "gen-5-14",
    "reference": "Genesis 5:14",
    "web": "and all of the days of Kenan were nine hundred ten years, then he died.",
    "kjv": "And all the days of Cainan were nine hundred and ten years: and he died."
  },
  "gen-5-15": {
    "id": "gen-5-15",
    "reference": "Genesis 5:15",
    "web": "Mahalalel lived sixty-five years, then became the father of Jared.",
    "kjv": "And Mahalaleel lived sixty and five years, and begat Jared:"
  },
  "gen-5-16": {
    "id": "gen-5-16",
    "reference": "Genesis 5:16",
    "web": "Mahalalel lived after he became the father of Jared eight hundred thirty years, and became the father of other sons and daughters.",
    "kjv": "And Mahalaleel lived after he begat Jared eight hundred and thirty years, and begat sons and daughters:"
  },
  "gen-5-17": {
    "id": "gen-5-17",
    "reference": "Genesis 5:17",
    "web": "All of the days of Mahalalel were eight hundred ninety-five years, then he died.",
    "kjv": "And all the days of Mahalaleel were eight hundred ninety and five years: and he died."
  },
  "gen-5-18": {
    "id": "gen-5-18",
    "reference": "Genesis 5:18",
    "web": "Jared lived one hundred sixty-two years, then became the father of Enoch.",
    "kjv": "And Jared lived an hundred sixty and two years, and he begat Enoch:"
  },
  "gen-5-19": {
    "id": "gen-5-19",
    "reference": "Genesis 5:19",
    "web": "Jared lived after he became the father of Enoch eight hundred years, and became the father of other sons and daughters.",
    "kjv": "And Jared lived after he begat Enoch eight hundred years, and begat sons and daughters:"
  },
  "gen-5-20": {
    "id": "gen-5-20",
    "reference": "Genesis 5:20",
    "web": "All of the days of Jared were nine hundred sixty-two years, then he died.",
    "kjv": "And all the days of Jared were nine hundred sixty and two years: and he died."
  },
  "gen-5-21": {
    "id": "gen-5-21",
    "reference": "Genesis 5:21",
    "web": "Enoch lived sixty-five years, then became the father of Methuselah.",
    "kjv": "And Enoch lived sixty and five years, and begat Methuselah:"
  },
  "gen-5-22": {
    "id": "gen-5-22",
    "reference": "Genesis 5:22",
    "web": "After Methuselah’s birth, Enoch walked with God for three hundred years, and became the father of more sons and daughters.",
    "kjv": "And Enoch walked with God after he begat Methuselah three hundred years, and begat sons and daughters:"
  },
  "gen-5-23": {
    "id": "gen-5-23",
    "reference": "Genesis 5:23",
    "web": "All the days of Enoch were three hundred sixty-five years.",
    "kjv": "And all the days of Enoch were three hundred sixty and five years:"
  },
  "gen-5-24": {
    "id": "gen-5-24",
    "reference": "Genesis 5:24",
    "web": "Enoch walked with God, and he was not found, for God took him.",
    "kjv": "And Enoch walked with God: and he was not; for God took him."
  },
  "gen-5-25": {
    "id": "gen-5-25",
    "reference": "Genesis 5:25",
    "web": "Methuselah lived one hundred eighty-seven years, then became the father of Lamech.",
    "kjv": "And Methuselah lived an hundred eighty and seven years, and begat Lamech:"
  },
  "gen-5-26": {
    "id": "gen-5-26",
    "reference": "Genesis 5:26",
    "web": "Methuselah lived after he became the father of Lamech seven hundred eighty-two years, and became the father of other sons and daughters.",
    "kjv": "And Methuselah lived after he begat Lamech seven hundred eighty and two years, and begat sons and daughters:"
  },
  "gen-5-27": {
    "id": "gen-5-27",
    "reference": "Genesis 5:27",
    "web": "All the days of Methuselah were nine hundred sixty-nine years, then he died.",
    "kjv": "And all the days of Methuselah were nine hundred sixty and nine years: and he died."
  },
  "gen-5-28": {
    "id": "gen-5-28",
    "reference": "Genesis 5:28",
    "web": "Lamech lived one hundred eighty-two years, then became the father of a son.",
    "kjv": "And Lamech lived an hundred eighty and two years, and begat a son:"
  },
  "gen-5-29": {
    "id": "gen-5-29",
    "reference": "Genesis 5:29",
    "web": "He named him Noah, saying, “This one will comfort us in our work and in the toil of our hands, caused by the ground which the LORD has cursed.”",
    "kjv": "And he called his name Noah, saying, This same shall comfort us concerning our work and toil of our hands, because of the ground which the LORD hath cursed."
  },
  "gen-5-30": {
    "id": "gen-5-30",
    "reference": "Genesis 5:30",
    "web": "Lamech lived after he became the father of Noah five hundred ninety-five years, and became the father of other sons and daughters.",
    "kjv": "And Lamech lived after he begat Noah five hundred ninety and five years, and begat sons and daughters:"
  },
  "gen-5-31": {
    "id": "gen-5-31",
    "reference": "Genesis 5:31",
    "web": "All the days of Lamech were seven hundred seventy-seven years, then he died.",
    "kjv": "And all the days of Lamech were seven hundred seventy and seven years: and he died."
  },
  "gen-5-32": {
    "id": "gen-5-32",
    "reference": "Genesis 5:32",
    "web": "Noah was five hundred years old, then Noah became the father of Shem, Ham, and Japheth.",
    "kjv": "And Noah was five hundred years old: and Noah begat Shem, Ham, and Japheth."
  },
  "gen-6-8": {
    "id": "gen-6-8",
    "reference": "Genesis 6:8",
    "web": "But Noah found favor in the LORD’s eyes.",
    "kjv": "But Noah found grace in the eyes of the LORD."
  },
  "gen-6-9": {
    "id": "gen-6-9",
    "reference": "Genesis 6:9",
    "web": "This is the history of the generations of Noah: Noah was a righteous man, blameless among the people of his time. Noah walked with God.",
    "kjv": "These are the generations of Noah: Noah was a just man and perfect in his generations, and Noah walked with God."
  },
  "gen-9-18": {
    "id": "gen-9-18",
    "reference": "Genesis 9:18",
    "web": "The sons of Noah who went out from the ship were Shem, Ham, and Japheth. Ham is the father of Canaan.",
    "kjv": "And the sons of Noah, that went forth of the ark, were Shem, and Ham, and Japheth: and Ham is the father of Canaan."
  },
  "gen-9-19": {
    "id": "gen-9-19",
    "reference": "Genesis 9:19",
    "web": "These three were the sons of Noah, and from these the whole earth was populated.",
    "kjv": "These are the three sons of Noah: and of them was the whole earth overspread."
  },
  "gen-11-10": {
    "id": "gen-11-10",
    "reference": "Genesis 11:10",
    "web": "This is the history of the generations of Shem: Shem was one hundred years old when he became the father of Arpachshad two years after the flood.",
    "kjv": "These are the generations of Shem: Shem was an hundred years old, and begat Arphaxad two years after the flood:"
  },
  "gen-11-11": {
    "id": "gen-11-11",
    "reference": "Genesis 11:11",
    "web": "Shem lived five hundred years after he became the father of Arpachshad, and became the father of more sons and daughters.",
    "kjv": "And Shem lived after he begat Arphaxad five hundred years, and begat sons and daughters."
  },
  "gen-11-12": {
    "id": "gen-11-12",
    "reference": "Genesis 11:12",
    "web": "Arpachshad lived thirty-five years and became the father of Shelah.",
    "kjv": "And Arphaxad lived five and thirty years, and begat Salah:"
  },
  "gen-11-13": {
    "id": "gen-11-13",
    "reference": "Genesis 11:13",
    "web": "Arpachshad lived four hundred three years after he became the father of Shelah, and became the father of more sons and daughters.",
    "kjv": "And Arphaxad lived after he begat Salah four hundred and three years, and begat sons and daughters."
  },
  "gen-11-14": {
    "id": "gen-11-14",
    "reference": "Genesis 11:14",
    "web": "Shelah lived thirty years, and became the father of Eber.",
    "kjv": "And Salah lived thirty years, and begat Eber:"
  },
  "gen-11-15": {
    "id": "gen-11-15",
    "reference": "Genesis 11:15",
    "web": "Shelah lived four hundred three years after he became the father of Eber, and became the father of more sons and daughters.",
    "kjv": "And Salah lived after he begat Eber four hundred and three years, and begat sons and daughters."
  },
  "gen-11-16": {
    "id": "gen-11-16",
    "reference": "Genesis 11:16",
    "web": "Eber lived thirty-four years, and became the father of Peleg.",
    "kjv": "And Eber lived four and thirty years, and begat Peleg:"
  },
  "gen-11-17": {
    "id": "gen-11-17",
    "reference": "Genesis 11:17",
    "web": "Eber lived four hundred thirty years after he became the father of Peleg, and became the father of more sons and daughters.",
    "kjv": "And Eber lived after he begat Peleg four hundred and thirty years, and begat sons and daughters."
  },
  "gen-11-18": {
    "id": "gen-11-18",
    "reference": "Genesis 11:18",
    "web": "Peleg lived thirty years, and became the father of Reu.",
    "kjv": "And Peleg lived thirty years, and begat Reu:"
  },
  "gen-11-19": {
    "id": "gen-11-19",
    "reference": "Genesis 11:19",
    "web": "Peleg lived two hundred nine years after he became the father of Reu, and became the father of more sons and daughters.",
    "kjv": "And Peleg lived after he begat Reu two hundred and nine years, and begat sons and daughters."
  },
  "gen-11-20": {
    "id": "gen-11-20",
    "reference": "Genesis 11:20",
    "web": "Reu lived thirty-two years, and became the father of Serug.",
    "kjv": "And Reu lived two and thirty years, and begat Serug:"
  },
  "gen-11-21": {
    "id": "gen-11-21",
    "reference": "Genesis 11:21",
    "web": "Reu lived two hundred seven years after he became the father of Serug, and became the father of more sons and daughters.",
    "kjv": "And Reu lived after he begat Serug two hundred and seven years, and begat sons and daughters."
  },
  "gen-11-22": {
    "id": "gen-11-22",
    "reference": "Genesis 11:22",
    "web": "Serug lived thirty years, and became the father of Nahor.",
    "kjv": "And Serug lived thirty years, and begat Nahor:"
  },
  "gen-11-23": {
    "id": "gen-11-23",
    "reference": "Genesis 11:23",
    "web": "Serug lived two hundred years after he became the father of Nahor, and became the father of more sons and daughters.",
    "kjv": "And Serug lived after he begat Nahor two hundred years, and begat sons and daughters."
  },
  "gen-11-24": {
    "id": "gen-11-24",
    "reference": "Genesis 11:24",
    "web": "Nahor lived twenty-nine years, and became the father of Terah.",
    "kjv": "And Nahor lived nine and twenty years, and begat Terah:"
  },
  "gen-11-25": {
    "id": "gen-11-25",
    "reference": "Genesis 11:25",
    "web": "Nahor lived one hundred nineteen years after he became the father of Terah, and became the father of more sons and daughters.",
    "kjv": "And Nahor lived after he begat Terah an hundred and nineteen years, and begat sons and daughters."
  },
  "gen-11-26": {
    "id": "gen-11-26",
    "reference": "Genesis 11:26",
    "web": "Terah lived seventy years, and became the father of Abram, Nahor, and Haran.",
    "kjv": "And Terah lived seventy years, and begat Abram, Nahor, and Haran."
  },
  "gen-11-27": {
    "id": "gen-11-27",
    "reference": "Genesis 11:27",
    "web": "Now this is the history of the generations of Terah. Terah became the father of Abram, Nahor, and Haran. Haran became the father of Lot.",
    "kjv": "Now these are the generations of Terah: Terah begat Abram, Nahor, and Haran; and Haran begat Lot."
  },
  "gen-11-28": {
    "id": "gen-11-28",
    "reference": "Genesis 11:28",
    "web": "Haran died in the land of his birth, in Ur of the Chaldees, while his father Terah was still alive.",
    "kjv": "And Haran died before his father Terah in the land of his nativity, in Ur of the Chaldees."
  },
  "gen-11-29": {
    "id": "gen-11-29",
    "reference": "Genesis 11:29",
    "web": "Abram and Nahor married wives. The name of Abram’s wife was Sarai, and the name of Nahor’s wife was Milcah, the daughter of Haran, who was also the father of Iscah.",
    "kjv": "And Abram and Nahor took them wives: the name of Abram’s wife was Sarai; and the name of Nahor’s wife, Milcah, the daughter of Haran, the father of Milcah, and the father of Iscah."
  },
  "gen-11-30": {
    "id": "gen-11-30",
    "reference": "Genesis 11:30",
    "web": "Sarai was barren. She had no child.",
    "kjv": "But Sarai was barren; she had no child."
  },
  "gen-11-31": {
    "id": "gen-11-31",
    "reference": "Genesis 11:31",
    "web": "Terah took Abram his son, Lot the son of Haran, his son’s son, and Sarai his daughter-in-law, his son Abram’s wife. They went from Ur of the Chaldees, to go into the land of Canaan. They came to Haran and lived there.",
    "kjv": "And Terah took Abram his son, and Lot the son of Haran his son’s son, and Sarai his daughter in law, his son Abram’s wife; and they went forth with them from Ur of the Chaldees, to go into the land of Canaan; and they came unto Haran, and dwelt there."
  },
  "gen-11-32": {
    "id": "gen-11-32",
    "reference": "Genesis 11:32",
    "web": "The days of Terah were two hundred five years. Terah died in Haran.",
    "kjv": "And the days of Terah were two hundred and five years: and Terah died in Haran."
  },
  "gen-12-1": {
    "id": "gen-12-1",
    "reference": "Genesis 12:1",
    "web": "Now the LORD said to Abram, “Leave your country, and your relatives, and your father’s house, and go to the land that I will show you.",
    "kjv": "Now the LORD had said unto Abram, Get thee out of thy country, and from thy kindred, and from thy father’s house, unto a land that I will shew thee:"
  },
  "gen-12-2": {
    "id": "gen-12-2",
    "reference": "Genesis 12:2",
    "web": "I will make of you a great nation. I will bless you and make your name great. You will be a blessing.",
    "kjv": "And I will make of thee a great nation, and I will bless thee, and make thy name great; and thou shalt be a blessing:"
  },
  "gen-12-3": {
    "id": "gen-12-3",
    "reference": "Genesis 12:3",
    "web": "I will bless those who bless you, and I will curse him who treats you with contempt. All the families of the earth will be blessed through you.”",
    "kjv": "And I will bless them that bless thee, and curse him that curseth thee: and in thee shall all families of the earth be blessed."
  },
  "gen-15-5": {
    "id": "gen-15-5",
    "reference": "Genesis 15:5",
    "web": "The LORD brought him outside, and said, “Look now toward the sky, and count the stars, if you are able to count them.” He said to Abram, “So your offspring will be.”",
    "kjv": "And he brought him forth abroad, and said, Look now toward heaven, and tell the stars, if thou be able to number them: and he said unto him, So shall thy seed be."
  },
  "gen-15-6": {
    "id": "gen-15-6",
    "reference": "Genesis 15:6",
    "web": "He believed in the LORD, who credited it to him for righteousness.",
    "kjv": "And he believed in the LORD; and he counted it to him for righteousness."
  },
  "gen-16-15": {
    "id": "gen-16-15",
    "reference": "Genesis 16:15",
    "web": "Hagar bore a son for Abram. Abram called the name of his son, whom Hagar bore, Ishmael.",
    "kjv": "And Hagar bare Abram a son: and Abram called his son’s name, which Hagar bare, Ishmael."
  },
  "gen-21-1": {
    "id": "gen-21-1",
    "reference": "Genesis 21:1",
    "web": "The LORD visited Sarah as he had said, and the LORD did to Sarah as he had spoken.",
    "kjv": "And the LORD visited Sarah as he had said, and the LORD did unto Sarah as he had spoken."
  },
  "gen-21-2": {
    "id": "gen-21-2",
    "reference": "Genesis 21:2",
    "web": "Sarah conceived, and bore Abraham a son in his old age, at the set time of which God had spoken to him.",
    "kjv": "For Sarah conceived, and bare Abraham a son in his old age, at the set time of which God had spoken to him."
  },
  "gen-21-3": {
    "id": "gen-21-3",
    "reference": "Genesis 21:3",
    "web": "Abraham called his son who was born to him, whom Sarah bore to him, Isaac.",
    "kjv": "And Abraham called the name of his son that was born unto him, whom Sarah bare to him, Isaac."
  },
  "gen-25-19": {
    "id": "gen-25-19",
    "reference": "Genesis 25:19",
    "web": "This is the history of the generations of Isaac, Abraham’s son. Abraham became the father of Isaac.",
    "kjv": "And these are the generations of Isaac, Abraham’s son: Abraham begat Isaac:"
  },
  "gen-25-20": {
    "id": "gen-25-20",
    "reference": "Genesis 25:20",
    "web": "Isaac was forty years old when he took Rebekah, the daughter of Bethuel the Syrian of Paddan Aram, the sister of Laban the Syrian, to be his wife.",
    "kjv": "And Isaac was forty years old when he took Rebekah to wife, the daughter of Bethuel the Syrian of Padan-aram, the sister to Laban the Syrian."
  },
  "gen-25-21": {
    "id": "gen-25-21",
    "reference": "Genesis 25:21",
    "web": "Isaac entreated the LORD for his wife, because she was barren. The LORD was entreated by him, and Rebekah his wife conceived.",
    "kjv": "And Isaac intreated the LORD for his wife, because she was barren: and the LORD was intreated of him, and Rebekah his wife conceived."
  },
  "gen-25-22": {
    "id": "gen-25-22",
    "reference": "Genesis 25:22",
    "web": "The children struggled together within her. She said, “If it is like this, why do I live?” She went to inquire of the LORD.",
    "kjv": "And the children struggled together within her; and she said, If it be so, why am I thus? And she went to enquire of the LORD."
  },
  "gen-25-23": {
    "id": "gen-25-23",
    "reference": "Genesis 25:23",
    "web": "The LORD said to her, “Two nations are in your womb. Two peoples will be separated from your body. The one people will be stronger than the other people. The elder will serve the younger.”",
    "kjv": "And the LORD said unto her, Two nations are in thy womb, and two manner of people shall be separated from thy bowels; and the one people shall be stronger than the other people; and the elder shall serve the younger."
  },
  "gen-25-24": {
    "id": "gen-25-24",
    "reference": "Genesis 25:24",
    "web": "When her days to be delivered were fulfilled, behold, there were twins in her womb.",
    "kjv": "And when her days to be delivered were fulfilled, behold, there were twins in her womb."
  },
  "gen-25-25": {
    "id": "gen-25-25",
    "reference": "Genesis 25:25",
    "web": "The first came out red all over, like a hairy garment. They named him Esau.",
    "kjv": "And the first came out red, all over like an hairy garment; and they called his name Esau."
  },
  "gen-25-26": {
    "id": "gen-25-26",
    "reference": "Genesis 25:26",
    "web": "After that, his brother came out, and his hand had hold on Esau’s heel. He was named Jacob. Isaac was sixty years old when she bore them.",
    "kjv": "And after that came his brother out, and his hand took hold on Esau’s heel; and his name was called Jacob: and Isaac was threescore years old when she bare them."
  },
  "gen-29-16": {
    "id": "gen-29-16",
    "reference": "Genesis 29:16",
    "web": "Laban had two daughters. The name of the elder was Leah, and the name of the younger was Rachel.",
    "kjv": "And Laban had two daughters: the name of the elder was Leah, and the name of the younger was Rachel."
  },
  "gen-29-17": {
    "id": "gen-29-17",
    "reference": "Genesis 29:17",
    "web": "Leah’s eyes were weak, but Rachel was beautiful in form and attractive.",
    "kjv": "Leah was tender eyed; but Rachel was beautiful and well favoured."
  },
  "gen-29-18": {
    "id": "gen-29-18",
    "reference": "Genesis 29:18",
    "web": "Jacob loved Rachel. He said, “I will serve you seven years for Rachel, your younger daughter.”",
    "kjv": "And Jacob loved Rachel; and said, I will serve thee seven years for Rachel thy younger daughter."
  },
  "gen-29-19": {
    "id": "gen-29-19",
    "reference": "Genesis 29:19",
    "web": "Laban said, “It is better that I give her to you, than that I should give her to another man. Stay with me.”",
    "kjv": "And Laban said, It is better that I give her to thee, than that I should give her to another man: abide with me."
  },
  "gen-29-20": {
    "id": "gen-29-20",
    "reference": "Genesis 29:20",
    "web": "Jacob served seven years for Rachel. They seemed to him but a few days, for the love he had for her.",
    "kjv": "And Jacob served seven years for Rachel; and they seemed unto him but a few days, for the love he had to her."
  },
  "gen-29-21": {
    "id": "gen-29-21",
    "reference": "Genesis 29:21",
    "web": "Jacob said to Laban, “Give me my wife, for my days are fulfilled, that I may go in to her.”",
    "kjv": "And Jacob said unto Laban, Give me my wife, for my days are fulfilled, that I may go in unto her."
  },
  "gen-29-22": {
    "id": "gen-29-22",
    "reference": "Genesis 29:22",
    "web": "Laban gathered together all the men of the place, and made a feast.",
    "kjv": "And Laban gathered together all the men of the place, and made a feast."
  },
  "gen-29-23": {
    "id": "gen-29-23",
    "reference": "Genesis 29:23",
    "web": "In the evening, he took Leah his daughter, and brought her to Jacob. He went in to her.",
    "kjv": "And it came to pass in the evening, that he took Leah his daughter, and brought her to him; and he went in unto her."
  },
  "gen-29-24": {
    "id": "gen-29-24",
    "reference": "Genesis 29:24",
    "web": "Laban gave Zilpah his servant to his daughter Leah for a servant.",
    "kjv": "And Laban gave unto his daughter Leah Zilpah his maid for an handmaid."
  },
  "gen-29-25": {
    "id": "gen-29-25",
    "reference": "Genesis 29:25",
    "web": "In the morning, behold, it was Leah! He said to Laban, “What is this you have done to me? Didn’t I serve with you for Rachel? Why then have you deceived me?”",
    "kjv": "And it came to pass, that in the morning, behold, it was Leah: and he said to Laban, What is this thou hast done unto me? did not I serve with thee for Rachel? wherefore then hast thou beguiled me?"
  },
  "gen-29-26": {
    "id": "gen-29-26",
    "reference": "Genesis 29:26",
    "web": "Laban said, “It is not done so in our place, to give the younger before the firstborn.",
    "kjv": "And Laban said, It must not be so done in our country, to give the younger before the firstborn."
  },
  "gen-29-27": {
    "id": "gen-29-27",
    "reference": "Genesis 29:27",
    "web": "Fulfill the week of this one, and we will give you the other also for the service which you will serve with me for seven more years.”",
    "kjv": "Fulfil her week, and we will give thee this also for the service which thou shalt serve with me yet seven other years."
  },
  "gen-29-28": {
    "id": "gen-29-28",
    "reference": "Genesis 29:28",
    "web": "Jacob did so, and fulfilled her week. He gave him Rachel his daughter as wife.",
    "kjv": "And Jacob did so, and fulfilled her week: and he gave him Rachel his daughter to wife also."
  },
  "gen-29-29": {
    "id": "gen-29-29",
    "reference": "Genesis 29:29",
    "web": "Laban gave Bilhah, his servant, to his daughter Rachel to be her servant.",
    "kjv": "And Laban gave to Rachel his daughter Bilhah his handmaid to be her maid."
  },
  "gen-29-30": {
    "id": "gen-29-30",
    "reference": "Genesis 29:30",
    "web": "He went in also to Rachel, and he loved also Rachel more than Leah, and served with him seven more years.",
    "kjv": "And he went in also unto Rachel, and he loved also Rachel more than Leah, and served with him yet seven other years."
  },
  "gen-29-31": {
    "id": "gen-29-31",
    "reference": "Genesis 29:31",
    "web": "The LORD saw that Leah was hated, and he opened her womb, but Rachel was barren.",
    "kjv": "And when the LORD saw that Leah was hated, he opened her womb: but Rachel was barren."
  },
  "gen-29-32": {
    "id": "gen-29-32",
    "reference": "Genesis 29:32",
    "web": "Leah conceived, and bore a son, and she named him Reuben. For she said, “Because the LORD has looked at my affliction; for now my husband will love me.”",
    "kjv": "And Leah conceived, and bare a son, and she called his name Reuben: for she said, Surely the LORD hath looked upon my affliction; now therefore my husband will love me."
  },
  "gen-29-33": {
    "id": "gen-29-33",
    "reference": "Genesis 29:33",
    "web": "She conceived again, and bore a son, and said, “Because the LORD has heard that I am hated, he has therefore given me this son also.” She named him Simeon.",
    "kjv": "And she conceived again, and bare a son; and said, Because the LORD hath heard that I was hated, he hath therefore given me this son also: and she called his name Simeon."
  },
  "gen-29-34": {
    "id": "gen-29-34",
    "reference": "Genesis 29:34",
    "web": "She conceived again, and bore a son. She said, “Now this time my husband will be joined to me, because I have borne him three sons.” Therefore his name was called Levi.",
    "kjv": "And she conceived again, and bare a son; and said, Now this time will my husband be joined unto me, because I have born him three sons: therefore was his name called Levi."
  },
  "gen-29-35": {
    "id": "gen-29-35",
    "reference": "Genesis 29:35",
    "web": "She conceived again, and bore a son. She said, “This time I will praise the LORD.” Therefore she named him Judah. Then she stopped bearing.",
    "kjv": "And she conceived again, and bare a son: and she said, Now will I praise the LORD: therefore she called his name Judah; and left bearing."
  },
  "gen-30-1": {
    "id": "gen-30-1",
    "reference": "Genesis 30:1",
    "web": "When Rachel saw that she bore Jacob no children, Rachel envied her sister. She said to Jacob, “Give me children, or else I will die.”",
    "kjv": "And when Rachel saw that she bare Jacob no children, Rachel envied her sister; and said unto Jacob, Give me children, or else I die."
  },
  "gen-30-2": {
    "id": "gen-30-2",
    "reference": "Genesis 30:2",
    "web": "Jacob’s anger burned against Rachel, and he said, “Am I in God’s place, who has withheld from you the fruit of the womb?”",
    "kjv": "And Jacob’s anger was kindled against Rachel: and he said, Am I in God’s stead, who hath withheld from thee the fruit of the womb?"
  },
  "gen-30-3": {
    "id": "gen-30-3",
    "reference": "Genesis 30:3",
    "web": "She said, “Behold, my maid Bilhah. Go in to her, that she may bear on my knees, and I also may obtain children by her.”",
    "kjv": "And she said, Behold my maid Bilhah, go in unto her; and she shall bear upon my knees, that I may also have children by her."
  },
  "gen-30-4": {
    "id": "gen-30-4",
    "reference": "Genesis 30:4",
    "web": "She gave him Bilhah her servant as wife, and Jacob went in to her.",
    "kjv": "And she gave him Bilhah her handmaid to wife: and Jacob went in unto her."
  },
  "gen-30-5": {
    "id": "gen-30-5",
    "reference": "Genesis 30:5",
    "web": "Bilhah conceived, and bore Jacob a son.",
    "kjv": "And Bilhah conceived, and bare Jacob a son."
  },
  "gen-30-6": {
    "id": "gen-30-6",
    "reference": "Genesis 30:6",
    "web": "Rachel said, “God has judged me, and has also heard my voice, and has given me a son.” Therefore she called his name Dan.",
    "kjv": "And Rachel said, God hath judged me, and hath also heard my voice, and hath given me a son: therefore called she his name Dan."
  },
  "gen-30-7": {
    "id": "gen-30-7",
    "reference": "Genesis 30:7",
    "web": "Bilhah, Rachel’s servant, conceived again, and bore Jacob a second son.",
    "kjv": "And Bilhah Rachel’s maid conceived again, and bare Jacob a second son."
  },
  "gen-30-8": {
    "id": "gen-30-8",
    "reference": "Genesis 30:8",
    "web": "Rachel said, “I have wrestled with my sister with mighty wrestlings, and have prevailed.” She named him Naphtali.",
    "kjv": "And Rachel said, With great wrestlings have I wrestled with my sister, and I have prevailed: and she called his name Naphtali."
  },
  "gen-30-9": {
    "id": "gen-30-9",
    "reference": "Genesis 30:9",
    "web": "When Leah saw that she had finished bearing, she took Zilpah, her servant, and gave her to Jacob as a wife.",
    "kjv": "When Leah saw that she had left bearing, she took Zilpah her maid, and gave her Jacob to wife."
  },
  "gen-30-10": {
    "id": "gen-30-10",
    "reference": "Genesis 30:10",
    "web": "Zilpah, Leah’s servant, bore Jacob a son.",
    "kjv": "And Zilpah Leah’s maid bare Jacob a son."
  },
  "gen-30-11": {
    "id": "gen-30-11",
    "reference": "Genesis 30:11",
    "web": "Leah said, “How fortunate!” She named him Gad.",
    "kjv": "And Leah said, A troop cometh: and she called his name Gad."
  },
  "gen-30-12": {
    "id": "gen-30-12",
    "reference": "Genesis 30:12",
    "web": "Zilpah, Leah’s servant, bore Jacob a second son.",
    "kjv": "And Zilpah Leah’s maid bare Jacob a second son."
  },
  "gen-30-13": {
    "id": "gen-30-13",
    "reference": "Genesis 30:13",
    "web": "Leah said, “Happy am I, for the daughters will call me happy.” She named him Asher.",
    "kjv": "And Leah said, Happy am I, for the daughters will call me blessed: and she called his name Asher."
  },
  "gen-30-14": {
    "id": "gen-30-14",
    "reference": "Genesis 30:14",
    "web": "Reuben went in the days of wheat harvest, and found mandrakes in the field, and brought them to his mother, Leah. Then Rachel said to Leah, “Please give me some of your son’s mandrakes.”",
    "kjv": "And Reuben went in the days of wheat harvest, and found mandrakes in the field, and brought them unto his mother Leah. Then Rachel said to Leah, Give me, I pray thee, of thy son’s mandrakes."
  },
  "gen-30-15": {
    "id": "gen-30-15",
    "reference": "Genesis 30:15",
    "web": "Leah said to her, “Is it a small matter that you have taken away my husband? Would you take away my son’s mandrakes, also?”\n\nRachel said, “Therefore he will lie with you tonight for your son’s mandrakes.”",
    "kjv": "And she said unto her, Is it a small matter that thou hast taken my husband? and wouldest thou take away my son’s mandrakes also? And Rachel said, Therefore he shall lie with thee to night for thy son’s mandrakes."
  },
  "gen-30-16": {
    "id": "gen-30-16",
    "reference": "Genesis 30:16",
    "web": "Jacob came from the field in the evening, and Leah went out to meet him, and said, “You must come in to me; for I have surely hired you with my son’s mandrakes.”\n\nHe lay with her that night.",
    "kjv": "And Jacob came out of the field in the evening, and Leah went out to meet him, and said, Thou must come in unto me; for surely I have hired thee with my son’s mandrakes. And he lay with her that night."
  },
  "gen-30-17": {
    "id": "gen-30-17",
    "reference": "Genesis 30:17",
    "web": "God listened to Leah, and she conceived, and bore Jacob a fifth son.",
    "kjv": "And God hearkened unto Leah, and she conceived, and bare Jacob the fifth son."
  },
  "gen-30-18": {
    "id": "gen-30-18",
    "reference": "Genesis 30:18",
    "web": "Leah said, “God has given me my hire, because I gave my servant to my husband.” She named him Issachar.",
    "kjv": "And Leah said, God hath given me my hire, because I have given my maiden to my husband: and she called his name Issachar."
  },
  "gen-30-19": {
    "id": "gen-30-19",
    "reference": "Genesis 30:19",
    "web": "Leah conceived again, and bore a sixth son to Jacob.",
    "kjv": "And Leah conceived again, and bare Jacob the sixth son."
  },
  "gen-30-20": {
    "id": "gen-30-20",
    "reference": "Genesis 30:20",
    "web": "Leah said, “God has endowed me with a good dowry. Now my husband will live with me, because I have borne him six sons.” She named him Zebulun.",
    "kjv": "And Leah said, God hath endued me with a good dowry; now will my husband dwell with me, because I have born him six sons: and she called his name Zebulun."
  },
  "gen-30-21": {
    "id": "gen-30-21",
    "reference": "Genesis 30:21",
    "web": "Afterwards, she bore a daughter, and named her Dinah.",
    "kjv": "And afterwards she bare a daughter, and called her name Dinah."
  },
  "gen-30-22": {
    "id": "gen-30-22",
    "reference": "Genesis 30:22",
    "web": "God remembered Rachel, and God listened to her, and opened her womb.",
    "kjv": "And God remembered Rachel, and God hearkened to her, and opened her womb."
  },
  "gen-30-23": {
    "id": "gen-30-23",
    "reference": "Genesis 30:23",
    "web": "She conceived, bore a son, and said, “God has taken away my reproach.”",
    "kjv": "And she conceived, and bare a son; and said, God hath taken away my reproach:"
  },
  "gen-30-24": {
    "id": "gen-30-24",
    "reference": "Genesis 30:24",
    "web": "She named him Joseph, saying, “May the LORD add another son to me.”",
    "kjv": "And she called his name Joseph; and said, The LORD shall add to me another son."
  },
  "gen-35-18": {
    "id": "gen-35-18",
    "reference": "Genesis 35:18",
    "web": "As her soul was departing (for she died), she named him Benoni, but his father named him Benjamin.",
    "kjv": "And it came to pass, as her soul was in departing, (for she died) that she called his name Ben-oni: but his father called him Benjamin."
  },
  "gen-35-19": {
    "id": "gen-35-19",
    "reference": "Genesis 35:19",
    "web": "Rachel died, and was buried on the way to Ephrath (also called Bethlehem).",
    "kjv": "And Rachel died, and was buried in the way to Ephrath, which is Beth-lehem."
  },
  "gen-35-20": {
    "id": "gen-35-20",
    "reference": "Genesis 35:20",
    "web": "Jacob set up a pillar on her grave. The same is the Pillar of Rachel’s grave to this day.",
    "kjv": "And Jacob set a pillar upon her grave: that is the pillar of Rachel’s grave unto this day."
  },
  "gen-35-21": {
    "id": "gen-35-21",
    "reference": "Genesis 35:21",
    "web": "Israel traveled, and spread his tent beyond the tower of Eder.",
    "kjv": "And Israel journeyed, and spread his tent beyond the tower of Edar."
  },
  "gen-35-22": {
    "id": "gen-35-22",
    "reference": "Genesis 35:22",
    "web": "While Israel lived in that land, Reuben went and lay with Bilhah, his father’s concubine, and Israel heard of it.\n\nNow the sons of Jacob were twelve.",
    "kjv": "And it came to pass, when Israel dwelt in that land, that Reuben went and lay with Bilhah his father’s concubine: and Israel heard it. Now the sons of Jacob were twelve:"
  },
  "gen-35-23": {
    "id": "gen-35-23",
    "reference": "Genesis 35:23",
    "web": "The sons of Leah: Reuben (Jacob’s firstborn), Simeon, Levi, Judah, Issachar, and Zebulun.",
    "kjv": "The sons of Leah; Reuben, Jacob’s firstborn, and Simeon, and Levi, and Judah, and Issachar, and Zebulun:"
  },
  "gen-35-24": {
    "id": "gen-35-24",
    "reference": "Genesis 35:24",
    "web": "The sons of Rachel: Joseph and Benjamin.",
    "kjv": "The sons of Rachel; Joseph, and Benjamin:"
  },
  "gen-35-25": {
    "id": "gen-35-25",
    "reference": "Genesis 35:25",
    "web": "The sons of Bilhah (Rachel’s servant): Dan and Naphtali.",
    "kjv": "And the sons of Bilhah, Rachel’s handmaid; Dan, and Naphtali:"
  },
  "gen-35-26": {
    "id": "gen-35-26",
    "reference": "Genesis 35:26",
    "web": "The sons of Zilpah (Leah’s servant): Gad and Asher. These are the sons of Jacob, who were born to him in Paddan Aram.",
    "kjv": "And the sons of Zilpah, Leah’s handmaid; Gad, and Asher: these are the sons of Jacob, which were born to him in Padan-aram."
  },
  "gen-38-6": {
    "id": "gen-38-6",
    "reference": "Genesis 38:6",
    "web": "Judah took a wife for Er, his firstborn, and her name was Tamar.",
    "kjv": "And Judah took a wife for Er his firstborn, whose name was Tamar."
  },
  "gen-38-7": {
    "id": "gen-38-7",
    "reference": "Genesis 38:7",
    "web": "Er, Judah’s firstborn, was wicked in the LORD’s sight. So the LORD killed him.",
    "kjv": "And Er, Judah’s firstborn, was wicked in the sight of the LORD; and the LORD slew him."
  },
  "gen-38-8": {
    "id": "gen-38-8",
    "reference": "Genesis 38:8",
    "web": "Judah said to Onan, “Go in to your brother’s wife, and perform the duty of a husband’s brother to her, and raise up offspring for your brother.”",
    "kjv": "And Judah said unto Onan, Go in unto thy brother’s wife, and marry her, and raise up seed to thy brother."
  },
  "gen-38-9": {
    "id": "gen-38-9",
    "reference": "Genesis 38:9",
    "web": "Onan knew that the offspring wouldn’t be his; and when he went in to his brother’s wife, he spilled his semen on the ground, lest he should give offspring to his brother.",
    "kjv": "And Onan knew that the seed should not be his; and it came to pass, when he went in unto his brother’s wife, that he spilled it on the ground, lest that he should give seed to his brother."
  },
  "gen-38-10": {
    "id": "gen-38-10",
    "reference": "Genesis 38:10",
    "web": "The thing which he did was evil in the LORD’s sight, and he killed him also.",
    "kjv": "And the thing which he did displeased the LORD: wherefore he slew him also."
  },
  "gen-38-11": {
    "id": "gen-38-11",
    "reference": "Genesis 38:11",
    "web": "Then Judah said to Tamar, his daughter-in-law, “Remain a widow in your father’s house, until Shelah, my son, is grown up;” for he said, “Lest he also die, like his brothers.” Tamar went and lived in her father’s house.",
    "kjv": "Then said Judah to Tamar his daughter in law, Remain a widow at thy father’s house, till Shelah my son be grown: for he said, Lest peradventure he die also, as his brethren did. And Tamar went and dwelt in her father’s house."
  },
  "gen-38-12": {
    "id": "gen-38-12",
    "reference": "Genesis 38:12",
    "web": "After many days, Shua’s daughter, the wife of Judah, died. Judah was comforted, and went up to his sheep shearers to Timnah, he and his friend Hirah, the Adullamite.",
    "kjv": "And in process of time the daughter of Shuah Judah’s wife died; and Judah was comforted, and went up unto his sheepshearers to Timnath, he and his friend Hirah the Adullamite."
  },
  "gen-38-13": {
    "id": "gen-38-13",
    "reference": "Genesis 38:13",
    "web": "Tamar was told, “Behold, your father-in-law is going up to Timnah to shear his sheep.”",
    "kjv": "And it was told Tamar, saying, Behold thy father in law goeth up to Timnath to shear his sheep."
  },
  "gen-38-14": {
    "id": "gen-38-14",
    "reference": "Genesis 38:14",
    "web": "She took off the garments of her widowhood, and covered herself with her veil, and wrapped herself, and sat in the gate of Enaim, which is on the way to Timnah; for she saw that Shelah was grown up, and she wasn’t given to him as a wife.",
    "kjv": "And she put her widow’s garments off from her, and covered her with a vail, and wrapped herself, and sat in an open place, which is by the way to Timnath; for she saw that Shelah was grown, and she was not given unto him to wife."
  },
  "gen-38-15": {
    "id": "gen-38-15",
    "reference": "Genesis 38:15",
    "web": "When Judah saw her, he thought that she was a prostitute, for she had covered her face.",
    "kjv": "When Judah saw her, he thought her to be an harlot; because she had covered her face."
  },
  "gen-38-16": {
    "id": "gen-38-16",
    "reference": "Genesis 38:16",
    "web": "He turned to her by the way, and said, “Please come, let me come in to you,” for he didn’t know that she was his daughter-in-law.\n\nShe said, “What will you give me, that you may come in to me?”",
    "kjv": "And he turned unto her by the way, and said, Go to, I pray thee, let me come in unto thee; (for he knew not that she was his daughter in law.) And she said, What wilt thou give me, that thou mayest come in unto me?"
  },
  "gen-38-17": {
    "id": "gen-38-17",
    "reference": "Genesis 38:17",
    "web": "He said, “I will send you a young goat from the flock.”\n\nShe said, “Will you give me a pledge, until you send it?”",
    "kjv": "And he said, I will send thee a kid from the flock. And she said, Wilt thou give me a pledge, till thou send it?"
  },
  "gen-38-18": {
    "id": "gen-38-18",
    "reference": "Genesis 38:18",
    "web": "He said, “What pledge will I give you?”\n\nShe said, “Your signet and your cord, and your staff that is in your hand.”\n\nHe gave them to her, and came in to her, and she conceived by him.",
    "kjv": "And he said, What pledge shall I give thee? And she said, Thy signet, and thy bracelets, and thy staff that is in thine hand. And he gave it her, and came in unto her, and she conceived by him."
  },
  "gen-38-19": {
    "id": "gen-38-19",
    "reference": "Genesis 38:19",
    "web": "She arose, and went away, and put off her veil from her, and put on the garments of her widowhood.",
    "kjv": "And she arose, and went away, and laid by her vail from her, and put on the garments of her widowhood."
  },
  "gen-38-20": {
    "id": "gen-38-20",
    "reference": "Genesis 38:20",
    "web": "Judah sent the young goat by the hand of his friend, the Adullamite, to receive the pledge from the woman’s hand, but he didn’t find her.",
    "kjv": "And Judah sent the kid by the hand of his friend the Adullamite, to receive his pledge from the woman’s hand: but he found her not."
  },
  "gen-38-21": {
    "id": "gen-38-21",
    "reference": "Genesis 38:21",
    "web": "Then he asked the men of her place, saying, “Where is the prostitute, that was at Enaim by the road?”\n\nThey said, “There has been no prostitute here.”",
    "kjv": "Then he asked the men of that place, saying, Where is the harlot, that was openly by the way side? And they said, There was no harlot in this place."
  },
  "gen-38-22": {
    "id": "gen-38-22",
    "reference": "Genesis 38:22",
    "web": "He returned to Judah, and said, “I haven’t found her; and also the men of the place said, ‘There has been no prostitute here.’”",
    "kjv": "And he returned to Judah, and said, I cannot find her; and also the men of the place said, that there was no harlot in this place."
  },
  "gen-38-23": {
    "id": "gen-38-23",
    "reference": "Genesis 38:23",
    "web": "Judah said, “Let her keep it, lest we be shamed. Behold, I sent this young goat, and you haven’t found her.”",
    "kjv": "And Judah said, Let her take it to her, lest we be shamed: behold, I sent this kid, and thou hast not found her."
  },
  "gen-38-24": {
    "id": "gen-38-24",
    "reference": "Genesis 38:24",
    "web": "About three months later, Judah was told, “Tamar, your daughter-in-law, has played the prostitute. Moreover, behold, she is with child by prostitution.”\n\nJudah said, “Bring her out, and let her be burned.”",
    "kjv": "And it came to pass about three months after, that it was told Judah, saying, Tamar thy daughter in law hath played the harlot; and also, behold, she is with child by whoredom. And Judah said, Bring her forth, and let her be burnt."
  },
  "gen-38-25": {
    "id": "gen-38-25",
    "reference": "Genesis 38:25",
    "web": "When she was brought out, she sent to her father-in-law, saying, “I am with child by the man who owns these.” She also said, “Please discern whose these are—the signet, and the cords, and the staff.”",
    "kjv": "When she was brought forth, she sent to her father in law, saying, By the man, whose these are, am I with child: and she said, Discern, I pray thee, whose are these, the signet, and bracelets, and staff."
  },
  "gen-38-26": {
    "id": "gen-38-26",
    "reference": "Genesis 38:26",
    "web": "Judah acknowledged them, and said, “She is more righteous than I, because I didn’t give her to Shelah, my son.”\n\nHe knew her again no more.",
    "kjv": "And Judah acknowledged them, and said, She hath been more righteous than I; because that I gave her not to Shelah my son. And he knew her again no more."
  },
  "gen-38-27": {
    "id": "gen-38-27",
    "reference": "Genesis 38:27",
    "web": "In the time of her travail, behold, twins were in her womb.",
    "kjv": "And it came to pass in the time of her travail, that, behold, twins were in her womb."
  },
  "gen-38-28": {
    "id": "gen-38-28",
    "reference": "Genesis 38:28",
    "web": "When she travailed, one put out a hand, and the midwife took and tied a scarlet thread on his hand, saying, “This came out first.”",
    "kjv": "And it came to pass, when she travailed, that the one put out his hand: and the midwife took and bound upon his hand a scarlet thread, saying, This came out first."
  },
  "gen-38-29": {
    "id": "gen-38-29",
    "reference": "Genesis 38:29",
    "web": "As he drew back his hand, behold, his brother came out, and she said, “Why have you made a breach for yourself?” Therefore his name was called Perez.",
    "kjv": "And it came to pass, as he drew back his hand, that, behold, his brother came out: and she said, How hast thou broken forth? this breach be upon thee: therefore his name was called Pharez."
  },
  "gen-38-30": {
    "id": "gen-38-30",
    "reference": "Genesis 38:30",
    "web": "Afterward his brother came out, who had the scarlet thread on his hand, and his name was called Zerah.",
    "kjv": "And afterward came out his brother, that had the scarlet thread upon his hand: and his name was called Zarah."
  },
  "josh-2-1": {
    "id": "josh-2-1",
    "reference": "Joshua 2:1",
    "web": "Joshua the son of Nun secretly sent two men out of Shittim as spies, saying, “Go, view the land, including Jericho.” They went and came into the house of a prostitute whose name was Rahab, and slept there.",
    "kjv": "And Joshua the son of Nun sent out of Shittim two men to spy secretly, saying, Go view the land, even Jericho. And they went, and came into an harlot’s house, named Rahab, and lodged there."
  },
  "josh-6-25": {
    "id": "josh-6-25",
    "reference": "Joshua 6:25",
    "web": "But Rahab the prostitute, her father’s household, and all that she had, Joshua saved alive. She lives in the middle of Israel to this day, because she hid the messengers whom Joshua sent to spy out Jericho.",
    "kjv": "And Joshua saved Rahab the harlot alive, and her father’s household, and all that she had; and she dwelleth in Israel even unto this day; because she hid the messengers, which Joshua sent to spy out Jericho."
  },
  "ruth-1-16": {
    "id": "ruth-1-16",
    "reference": "Ruth 1:16",
    "web": "Ruth said, “Don’t urge me to leave you, and to return from following you, for where you go, I will go; and where you stay, I will stay. Your people will be my people, and your God my God.",
    "kjv": "And Ruth said, Intreat me not to leave thee, or to return from following after thee: for whither thou goest, I will go; and where thou lodgest, I will lodge: thy people shall be my people, and thy God my God:"
  },
  "ruth-1-17": {
    "id": "ruth-1-17",
    "reference": "Ruth 1:17",
    "web": "Where you die, I will die, and there I will be buried. May the LORD do so to me, and more also, if anything but death parts you and me.”",
    "kjv": "Where thou diest, will I die, and there will I be buried: the LORD do so to me, and more also, if ought but death part thee and me."
  },
  "ruth-2-1": {
    "id": "ruth-2-1",
    "reference": "Ruth 2:1",
    "web": "Naomi had a relative of her husband’s, a mighty man of wealth, of the family of Elimelech, and his name was Boaz.",
    "kjv": "And Naomi had a kinsman of her husband’s, a mighty man of wealth, of the family of Elimelech; and his name was Boaz."
  },
  "ruth-4-9": {
    "id": "ruth-4-9",
    "reference": "Ruth 4:9",
    "web": "Boaz said to the elders and to all the people, “You are witnesses today, that I have bought all that was Elimelech’s, and all that was Chilion’s and Mahlon’s, from the hand of Naomi.",
    "kjv": "And Boaz said unto the elders, and unto all the people, Ye are witnesses this day, that I have bought all that was Elimelech’s, and all that was Chilion’s and Mahlon’s, of the hand of Naomi."
  },
  "ruth-4-10": {
    "id": "ruth-4-10",
    "reference": "Ruth 4:10",
    "web": "Moreover, Ruth the Moabitess, the wife of Mahlon, I have purchased to be my wife, to raise up the name of the dead on his inheritance, that the name of the dead may not be cut off from among his brothers and from the gate of his place. You are witnesses today.”",
    "kjv": "Moreover Ruth the Moabitess, the wife of Mahlon, have I purchased to be my wife, to raise up the name of the dead upon his inheritance, that the name of the dead be not cut off from among his brethren, and from the gate of his place: ye are witnesses this day."
  },
  "ruth-4-11": {
    "id": "ruth-4-11",
    "reference": "Ruth 4:11",
    "web": "All the people who were in the gate, and the elders, said, “We are witnesses. May the LORD make the woman who has come into your house like Rachel and like Leah, which both built the house of Israel; and treat you worthily in Ephrathah, and be famous in Bethlehem.",
    "kjv": "And all the people that were in the gate, and the elders, said, We are witnesses. The LORD make the woman that is come into thine house like Rachel and like Leah, which two did build the house of Israel: and do thou worthily in Ephratah, and be famous in Beth-lehem:"
  },
  "ruth-4-12": {
    "id": "ruth-4-12",
    "reference": "Ruth 4:12",
    "web": "Let your house be like the house of Perez, whom Tamar bore to Judah, of the offspring which the LORD will give you by this young woman.”",
    "kjv": "And let thy house be like the house of Pharez, whom Tamar bare unto Judah, of the seed which the LORD shall give thee of this young woman."
  },
  "ruth-4-13": {
    "id": "ruth-4-13",
    "reference": "Ruth 4:13",
    "web": "So Boaz took Ruth and she became his wife; and he went in to her, and the LORD enabled her to conceive, and she bore a son.",
    "kjv": "So Boaz took Ruth, and she was his wife: and when he went in unto her, the LORD gave her conception, and she bare a son."
  },
  "ruth-4-14": {
    "id": "ruth-4-14",
    "reference": "Ruth 4:14",
    "web": "The women said to Naomi, “Blessed be the LORD, who has not left you today without a near kinsman. Let his name be famous in Israel.",
    "kjv": "And the women said unto Naomi, Blessed be the LORD, which hath not left thee this day without a kinsman, that his name may be famous in Israel."
  },
  "ruth-4-15": {
    "id": "ruth-4-15",
    "reference": "Ruth 4:15",
    "web": "He shall be to you a restorer of life and sustain you in your old age; for your daughter-in-law, who loves you, who is better to you than seven sons, has given birth to him.”",
    "kjv": "And he shall be unto thee a restorer of thy life, and a nourisher of thine old age: for thy daughter in law, which loveth thee, which is better to thee than seven sons, hath born him."
  },
  "ruth-4-16": {
    "id": "ruth-4-16",
    "reference": "Ruth 4:16",
    "web": "Naomi took the child, laid him in her bosom, and became nurse to him.",
    "kjv": "And Naomi took the child, and laid it in her bosom, and became nurse unto it."
  },
  "ruth-4-17": {
    "id": "ruth-4-17",
    "reference": "Ruth 4:17",
    "web": "The women, her neighbors, gave him a name, saying, “A son is born to Naomi”. They named him Obed. He is the father of Jesse, the father of David.",
    "kjv": "And the women her neighbours gave it a name, saying, There is a son born to Naomi; and they called his name Obed: he is the father of Jesse, the father of David."
  },
  "ruth-4-18": {
    "id": "ruth-4-18",
    "reference": "Ruth 4:18",
    "web": "Now this is the history of the generations of Perez: Perez became the father of Hezron,",
    "kjv": "Now these are the generations of Pharez: Pharez begat Hezron,"
  },
  "ruth-4-19": {
    "id": "ruth-4-19",
    "reference": "Ruth 4:19",
    "web": "and Hezron became the father of Ram, and Ram became the father of Amminadab,",
    "kjv": "And Hezron begat Ram, and Ram begat Amminadab,"
  },
  "ruth-4-20": {
    "id": "ruth-4-20",
    "reference": "Ruth 4:20",
    "web": "and Amminadab became the father of Nahshon, and Nahshon became the father of Salmon,",
    "kjv": "And Amminadab begat Nahshon, and Nahshon begat Salmon,"
  },
  "ruth-4-21": {
    "id": "ruth-4-21",
    "reference": "Ruth 4:21",
    "web": "and Salmon became the father of Boaz, and Boaz became the father of Obed,",
    "kjv": "And Salmon begat Boaz, and Boaz begat Obed,"
  },
  "ruth-4-22": {
    "id": "ruth-4-22",
    "reference": "Ruth 4:22",
    "web": "and Obed became the father of Jesse, and Jesse became the father of David.",
    "kjv": "And Obed begat Jesse, and Jesse begat David."
  },
  "1-sam-16-12": {
    "id": "1-sam-16-12",
    "reference": "1 Samuel 16:12",
    "web": "He sent, and brought him in. Now he was ruddy, with a handsome face and good appearance. The LORD said, “Arise! Anoint him, for this is he.”",
    "kjv": "And he sent, and brought him in. Now he was ruddy, and withal of a beautiful countenance, and goodly to look to. And the LORD said, Arise, anoint him: for this is he."
  },
  "1-sam-16-13": {
    "id": "1-sam-16-13",
    "reference": "1 Samuel 16:13",
    "web": "Then Samuel took the horn of oil and anointed him in the middle of his brothers. Then the LORD’s Spirit came mightily on David from that day forward. So Samuel rose up and went to Ramah.",
    "kjv": "Then Samuel took the horn of oil, and anointed him in the midst of his brethren: and the Spirit of the LORD came upon David from that day forward. So Samuel rose up, and went to Ramah."
  },
  "2-sam-7-12": {
    "id": "2-sam-7-12",
    "reference": "2 Samuel 7:12",
    "web": "When your days are fulfilled and you sleep with your fathers, I will set up your offspring after you, who will proceed out of your body, and I will establish his kingdom.",
    "kjv": "And when thy days be fulfilled, and thou shalt sleep with thy fathers, I will set up thy seed after thee, which shall proceed out of thy bowels, and I will establish his kingdom."
  },
  "2-sam-7-13": {
    "id": "2-sam-7-13",
    "reference": "2 Samuel 7:13",
    "web": "He will build a house for my name, and I will establish the throne of his kingdom forever.",
    "kjv": "He shall build an house for my name, and I will stablish the throne of his kingdom for ever."
  },
  "2-sam-7-14": {
    "id": "2-sam-7-14",
    "reference": "2 Samuel 7:14",
    "web": "I will be his father, and he will be my son. If he commits iniquity, I will chasten him with the rod of men and with the stripes of the children of men;",
    "kjv": "I will be his father, and he shall be my son. If he commit iniquity, I will chasten him with the rod of men, and with the stripes of the children of men:"
  },
  "2-sam-7-15": {
    "id": "2-sam-7-15",
    "reference": "2 Samuel 7:15",
    "web": "but my loving kindness will not depart from him, as I took it from Saul, whom I put away before you.",
    "kjv": "But my mercy shall not depart away from him, as I took it from Saul, whom I put away before thee."
  },
  "2-sam-7-16": {
    "id": "2-sam-7-16",
    "reference": "2 Samuel 7:16",
    "web": "Your house and your kingdom will be made sure forever before you. Your throne will be established forever.”’”",
    "kjv": "And thine house and thy kingdom shall be established for ever before thee: thy throne shall be established for ever."
  },
  "2-sam-12-24": {
    "id": "2-sam-12-24",
    "reference": "2 Samuel 12:24",
    "web": "David comforted Bathsheba his wife, and went in to her, and lay with her. She bore a son, and he called his name Solomon. The LORD loved him;",
    "kjv": "And David comforted Bath-sheba his wife, and went in unto her, and lay with her: and she bare a son, and he called his name Solomon: and the LORD loved him."
  },
  "2-sam-12-25": {
    "id": "2-sam-12-25",
    "reference": "2 Samuel 12:25",
    "web": "and he sent by the hand of Nathan the prophet, and he named him Jedidiah, for the LORD’s sake.",
    "kjv": "And he sent by the hand of Nathan the prophet; and he called his name Jedidiah, because of the LORD."
  },
  "matt-1-1": {
    "id": "matt-1-1",
    "reference": "Matthew 1:1",
    "web": "The book of the genealogy of Jesus Christ, the son of David, the son of Abraham.",
    "kjv": "The book of the generation of Jesus Christ, the son of David, the son of Abraham."
  },
  "matt-1-2": {
    "id": "matt-1-2",
    "reference": "Matthew 1:2",
    "web": "Abraham became the father of Isaac. Isaac became the father of Jacob. Jacob became the father of Judah and his brothers.",
    "kjv": "Abraham begat Isaac; and Isaac begat Jacob; and Jacob begat Judas and his brethren;"
  },
  "matt-1-3": {
    "id": "matt-1-3",
    "reference": "Matthew 1:3",
    "web": "Judah became the father of Perez and Zerah by Tamar. Perez became the father of Hezron. Hezron became the father of Ram.",
    "kjv": "And Judas begat Phares and Zara of Thamar; and Phares begat Esrom; and Esrom begat Aram;"
  },
  "matt-1-4": {
    "id": "matt-1-4",
    "reference": "Matthew 1:4",
    "web": "Ram became the father of Amminadab. Amminadab became the father of Nahshon. Nahshon became the father of Salmon.",
    "kjv": "And Aram begat Aminadab; and Aminadab begat Naasson; and Naasson begat Salmon;"
  },
  "matt-1-5": {
    "id": "matt-1-5",
    "reference": "Matthew 1:5",
    "web": "Salmon became the father of Boaz by Rahab. Boaz became the father of Obed by Ruth. Obed became the father of Jesse.",
    "kjv": "And Salmon begat Booz of Rachab; and Booz begat Obed of Ruth; and Obed begat Jesse;"
  },
  "matt-1-6": {
    "id": "matt-1-6",
    "reference": "Matthew 1:6",
    "web": "Jesse became the father of King David. David the king became the father of Solomon by her who had been Uriah’s wife.",
    "kjv": "And Jesse begat David the king; and David the king begat Solomon of her that had been the wife of Urias;"
  },
  "matt-1-7": {
    "id": "matt-1-7",
    "reference": "Matthew 1:7",
    "web": "Solomon became the father of Rehoboam. Rehoboam became the father of Abijah. Abijah became the father of Asa.",
    "kjv": "And Solomon begat Roboam; and Roboam begat Abia; and Abia begat Asa;"
  },
  "matt-1-8": {
    "id": "matt-1-8",
    "reference": "Matthew 1:8",
    "web": "Asa became the father of Jehoshaphat. Jehoshaphat became the father of Joram. Joram became the father of Uzziah.",
    "kjv": "And Asa begat Josaphat; and Josaphat begat Joram; and Joram begat Ozias;"
  },
  "matt-1-9": {
    "id": "matt-1-9",
    "reference": "Matthew 1:9",
    "web": "Uzziah became the father of Jotham. Jotham became the father of Ahaz. Ahaz became the father of Hezekiah.",
    "kjv": "And Ozias begat Joatham; and Joatham begat Achaz; and Achaz begat Ezekias;"
  },
  "matt-1-10": {
    "id": "matt-1-10",
    "reference": "Matthew 1:10",
    "web": "Hezekiah became the father of Manasseh. Manasseh became the father of Amon. Amon became the father of Josiah.",
    "kjv": "And Ezekias begat Manasses; and Manasses begat Amon; and Amon begat Josias;"
  },
  "matt-1-11": {
    "id": "matt-1-11",
    "reference": "Matthew 1:11",
    "web": "Josiah became the father of Jechoniah and his brothers at the time of the exile to Babylon.",
    "kjv": "And Josias begat Jechonias and his brethren, about the time they were carried away to Babylon:"
  },
  "matt-1-12": {
    "id": "matt-1-12",
    "reference": "Matthew 1:12",
    "web": "After the exile to Babylon, Jechoniah became the father of Shealtiel. Shealtiel became the father of Zerubbabel.",
    "kjv": "And after they were brought to Babylon, Jechonias begat Salathiel; and Salathiel begat Zorobabel;"
  },
  "matt-1-13": {
    "id": "matt-1-13",
    "reference": "Matthew 1:13",
    "web": "Zerubbabel became the father of Abiud. Abiud became the father of Eliakim. Eliakim became the father of Azor.",
    "kjv": "And Zorobabel begat Abiud; and Abiud begat Eliakim; and Eliakim begat Azor;"
  },
  "matt-1-14": {
    "id": "matt-1-14",
    "reference": "Matthew 1:14",
    "web": "Azor became the father of Zadok. Zadok became the father of Achim. Achim became the father of Eliud.",
    "kjv": "And Azor begat Sadoc; and Sadoc begat Achim; and Achim begat Eliud;"
  },
  "matt-1-15": {
    "id": "matt-1-15",
    "reference": "Matthew 1:15",
    "web": "Eliud became the father of Eleazar. Eleazar became the father of Matthan. Matthan became the father of Jacob.",
    "kjv": "And Eliud begat Eleazar; and Eleazar begat Matthan; and Matthan begat Jacob;"
  },
  "matt-1-16": {
    "id": "matt-1-16",
    "reference": "Matthew 1:16",
    "web": "Jacob became the father of Joseph, the husband of Mary, from whom was born Jesus, who is called Christ.",
    "kjv": "And Jacob begat Joseph the husband of Mary, of whom was born Jesus, who is called Christ."
  },
  "matt-1-17": {
    "id": "matt-1-17",
    "reference": "Matthew 1:17",
    "web": "So all the generations from Abraham to David are fourteen generations; from David to the exile to Babylon fourteen generations; and from the carrying away to Babylon to the Christ, fourteen generations.",
    "kjv": "So all the generations from Abraham to David are fourteen generations; and from David until the carrying away into Babylon are fourteen generations; and from the carrying away into Babylon unto Christ are fourteen generations."
  },
  "matt-1-18": {
    "id": "matt-1-18",
    "reference": "Matthew 1:18",
    "web": "Now the birth of Jesus Christ was like this: After his mother, Mary, was engaged to Joseph, before they came together, she was found pregnant by the Holy Spirit.",
    "kjv": "Now the birth of Jesus Christ was on this wise: When as his mother Mary was espoused to Joseph, before they came together, she was found with child of the Holy Ghost."
  },
  "matt-1-19": {
    "id": "matt-1-19",
    "reference": "Matthew 1:19",
    "web": "Joseph, her husband, being a righteous man, and not willing to make her a public example, intended to put her away secretly.",
    "kjv": "Then Joseph her husband, being a just man, and not willing to make her a publick example, was minded to put her away privily."
  },
  "matt-1-20": {
    "id": "matt-1-20",
    "reference": "Matthew 1:20",
    "web": "But when he thought about these things, behold, an angel of the Lord appeared to him in a dream, saying, “Joseph, son of David, don’t be afraid to take to yourself Mary as your wife, for that which is conceived in her is of the Holy Spirit.",
    "kjv": "But while he thought on these things, behold, the angel of the Lord appeared unto him in a dream, saying, Joseph, thou son of David, fear not to take unto thee Mary thy wife: for that which is conceived in her is of the Holy Ghost."
  },
  "matt-1-21": {
    "id": "matt-1-21",
    "reference": "Matthew 1:21",
    "web": "She shall give birth to a son. You shall name him Jesus, for it is he who shall save his people from their sins.”",
    "kjv": "And she shall bring forth a son, and thou shalt call his name JESUS: for he shall save his people from their sins."
  },
  "luke-1-30": {
    "id": "luke-1-30",
    "reference": "Luke 1:30",
    "web": "The angel said to her, “Don’t be afraid, Mary, for you have found favor with God.",
    "kjv": "And the angel said unto her, Fear not, Mary: for thou hast found favour with God."
  },
  "luke-1-31": {
    "id": "luke-1-31",
    "reference": "Luke 1:31",
    "web": "Behold, you will conceive in your womb and give birth to a son, and shall name him ‘Jesus.’",
    "kjv": "And, behold, thou shalt conceive in thy womb, and bring forth a son, and shalt call his name JESUS."
  },
  "luke-1-32": {
    "id": "luke-1-32",
    "reference": "Luke 1:32",
    "web": "He will be great and will be called the Son of the Most High. The Lord God will give him the throne of his father David,",
    "kjv": "He shall be great, and shall be called the Son of the Highest: and the Lord God shall give unto him the throne of his father David:"
  },
  "luke-1-33": {
    "id": "luke-1-33",
    "reference": "Luke 1:33",
    "web": "and he will reign over the house of Jacob forever. There will be no end to his Kingdom.”",
    "kjv": "And he shall reign over the house of Jacob for ever; and of his kingdom there shall be no end."
  },
  "luke-1-34": {
    "id": "luke-1-34",
    "reference": "Luke 1:34",
    "web": "Mary said to the angel, “How can this be, seeing I am a virgin?”",
    "kjv": "Then said Mary unto the angel, How shall this be, seeing I know not a man?"
  },
  "luke-1-35": {
    "id": "luke-1-35",
    "reference": "Luke 1:35",
    "web": "The angel answered her, “The Holy Spirit will come on you, and the power of the Most High will overshadow you. Therefore also the holy one who is born from you will be called the Son of God.",
    "kjv": "And the angel answered and said unto her, The Holy Ghost shall come upon thee, and the power of the Highest shall overshadow thee: therefore also that holy thing which shall be born of thee shall be called the Son of God."
  },
  "luke-3-23": {
    "id": "luke-3-23",
    "reference": "Luke 3:23",
    "web": "Jesus himself, when he began to teach, was about thirty years old, being the son (as was supposed) of Joseph, the son of Heli,",
    "kjv": "And Jesus himself began to be about thirty years of age, being (as was supposed) the son of Joseph, which was the son of Heli,"
  },
  "luke-3-24": {
    "id": "luke-3-24",
    "reference": "Luke 3:24",
    "web": "the son of Matthat, the son of Levi, the son of Melchi, the son of Jannai, the son of Joseph,",
    "kjv": "Which was the son of Matthat, which was the son of Levi, which was the son of Melchi, which was the son of Janna, which was the son of Joseph,"
  },
  "luke-3-25": {
    "id": "luke-3-25",
    "reference": "Luke 3:25",
    "web": "the son of Mattathias, the son of Amos, the son of Nahum, the son of Esli, the son of Naggai,",
    "kjv": "Which was the son of Mattathias, which was the son of Amos, which was the son of Naum, which was the son of Esli, which was the son of Nagge,"
  },
  "luke-3-26": {
    "id": "luke-3-26",
    "reference": "Luke 3:26",
    "web": "the son of Maath, the son of Mattathias, the son of Semein, the son of Joseph, the son of Judah,",
    "kjv": "Which was the son of Maath, which was the son of Mattathias, which was the son of Semei, which was the son of Joseph, which was the son of Juda,"
  },
  "luke-3-27": {
    "id": "luke-3-27",
    "reference": "Luke 3:27",
    "web": "the son of Joanan, the son of Rhesa, the son of Zerubbabel, the son of Shealtiel, the son of Neri,",
    "kjv": "Which was the son of Joanna, which was the son of Rhesa, which was the son of Zorobabel, which was the son of Salathiel, which was the son of Neri,"
  },
  "luke-3-28": {
    "id": "luke-3-28",
    "reference": "Luke 3:28",
    "web": "the son of Melchi, the son of Addi, the son of Cosam, the son of Elmodam, the son of Er,",
    "kjv": "Which was the son of Melchi, which was the son of Addi, which was the son of Cosam, which was the son of Elmodam, which was the son of Er,"
  },
  "luke-3-29": {
    "id": "luke-3-29",
    "reference": "Luke 3:29",
    "web": "the son of Jose, the son of Eliezer, the son of Jorim, the son of Matthat, the son of Levi,",
    "kjv": "Which was the son of Jose, which was the son of Eliezer, which was the son of Jorim, which was the son of Matthat, which was the son of Levi,"
  },
  "luke-3-30": {
    "id": "luke-3-30",
    "reference": "Luke 3:30",
    "web": "the son of Simeon, the son of Judah, the son of Joseph, the son of Jonan, the son of Eliakim,",
    "kjv": "Which was the son of Simeon, which was the son of Juda, which was the son of Joseph, which was the son of Jonan, which was the son of Eliakim,"
  },
  "luke-3-31": {
    "id": "luke-3-31",
    "reference": "Luke 3:31",
    "web": "the son of Melea, the son of Menan, the son of Mattatha, the son of Nathan, the son of David,",
    "kjv": "Which was the son of Melea, which was the son of Menan, which was the son of Mattatha, which was the son of Nathan, which was the son of David,"
  },
  "luke-3-32": {
    "id": "luke-3-32",
    "reference": "Luke 3:32",
    "web": "the son of Jesse, the son of Obed, the son of Boaz, the son of Salmon, the son of Nahshon,",
    "kjv": "Which was the son of Jesse, which was the son of Obed, which was the son of Booz, which was the son of Salmon, which was the son of Naasson,"
  },
  "luke-3-33": {
    "id": "luke-3-33",
    "reference": "Luke 3:33",
    "web": "the son of Amminadab, the son of Aram, the son of Hezron, the son of Perez, the son of Judah,",
    "kjv": "Which was the son of Aminadab, which was the son of Aram, which was the son of Esrom, which was the son of Phares, which was the son of Juda,"
  },
  "luke-3-34": {
    "id": "luke-3-34",
    "reference": "Luke 3:34",
    "web": "the son of Jacob, the son of Isaac, the son of Abraham, the son of Terah, the son of Nahor,",
    "kjv": "Which was the son of Jacob, which was the son of Isaac, which was the son of Abraham, which was the son of Thara, which was the son of Nachor,"
  },
  "luke-3-35": {
    "id": "luke-3-35",
    "reference": "Luke 3:35",
    "web": "the son of Serug, the son of Reu, the son of Peleg, the son of Eber, the son of Shelah,",
    "kjv": "Which was the son of Saruch, which was the son of Ragau, which was the son of Phalec, which was the son of Heber, which was the son of Sala,"
  },
  "luke-3-36": {
    "id": "luke-3-36",
    "reference": "Luke 3:36",
    "web": "the son of Cainan, the son of Arphaxad, the son of Shem, the son of Noah, the son of Lamech,",
    "kjv": "Which was the son of Cainan, which was the son of Arphaxad, which was the son of Sem, which was the son of Noe, which was the son of Lamech,"
  },
  "luke-3-37": {
    "id": "luke-3-37",
    "reference": "Luke 3:37",
    "web": "the son of Methuselah, the son of Enoch, the son of Jared, the son of Mahalaleel, the son of Cainan,",
    "kjv": "Which was the son of Mathusala, which was the son of Enoch, which was the son of Jared, which was the son of Maleleel, which was the son of Cainan,"
  },
  "luke-3-38": {
    "id": "luke-3-38",
    "reference": "Luke 3:38",
    "web": "the son of Enos, the son of Seth, the son of Adam, the son of God.",
    "kjv": "Which was the son of Enos, which was the son of Seth, which was the son of Adam, which was the son of God."
  },
  "heb-11-5": {
    "id": "heb-11-5",
    "reference": "Hebrews 11:5",
    "web": "By faith Enoch was taken away, so that he wouldn’t see death, and he was not found, because God translated him. For he has had testimony given to him that before his translation he had been well pleasing to God.",
    "kjv": "By faith Enoch was translated that he should not see death; and was not found, because God had translated him: for before his translation he had this testimony, that he pleased God."
  },
  "heb-11-6": {
    "id": "heb-11-6",
    "reference": "Hebrews 11:6",
    "web": "Without faith it is impossible to be well pleasing to him, for he who comes to God must believe that he exists, and that he is a rewarder of those who seek him.",
    "kjv": "But without faith it is impossible to please him: for he that cometh to God must believe that he is, and that he is a rewarder of them that diligently seek him."
  },
  "heb-11-7": {
    "id": "heb-11-7",
    "reference": "Hebrews 11:7",
    "web": "By faith Noah, being warned about things not yet seen, moved with godly fear, prepared a ship for the saving of his house, through which he condemned the world and became heir of the righteousness which is according to faith.",
    "kjv": "By faith Noah, being warned of God of things not seen as yet, moved with fear, prepared an ark to the saving of his house; by the which he condemned the world, and became heir of the righteousness which is by faith."
  },
  "heb-11-8": {
    "id": "heb-11-8",
    "reference": "Hebrews 11:8",
    "web": "By faith Abraham, when he was called, obeyed to go out to the place which he was to receive for an inheritance. He went out, not knowing where he went.",
    "kjv": "By faith Abraham, when he was called to go out into a place which he should after receive for an inheritance, obeyed; and he went out, not knowing whither he went."
  },
  "heb-11-9": {
    "id": "heb-11-9",
    "reference": "Hebrews 11:9",
    "web": "By faith he lived as an alien in the land of promise, as in a land not his own, dwelling in tents with Isaac and Jacob, the heirs with him of the same promise.",
    "kjv": "By faith he sojourned in the land of promise, as in a strange country, dwelling in tabernacles with Isaac and Jacob, the heirs with him of the same promise:"
  },
  "heb-11-10": {
    "id": "heb-11-10",
    "reference": "Hebrews 11:10",
    "web": "For he was looking for the city which has foundations, whose builder and maker is God.",
    "kjv": "For he looked for a city which hath foundations, whose builder and maker is God."
  },
  "heb-11-11": {
    "id": "heb-11-11",
    "reference": "Hebrews 11:11",
    "web": "By faith even Sarah herself received power to conceive, and she bore a child when she was past age, since she counted him faithful who had promised.",
    "kjv": "Through faith also Sara herself received strength to conceive seed, and was delivered of a child when she was past age, because she judged him faithful who had promised."
  },
  "heb-11-31": {
    "id": "heb-11-31",
    "reference": "Hebrews 11:31",
    "web": "By faith Rahab the prostitute didn’t perish with those who were disobedient, having received the spies in peace.",
    "kjv": "By faith the harlot Rahab perished not with them that believed not, when she had received the spies with peace."
  },
  "jas-2-25": {
    "id": "jas-2-25",
    "reference": "James 2:25",
    "web": "In the same way, wasn’t Rahab the prostitute also justified by works when she received the messengers and sent them out another way?",
    "kjv": "Likewise also was not Rahab the harlot justified by works, when she had received the messengers, and had sent them out another way?"
  }
};
